---
- name: "create folder for backend app"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: "PM2 run node app"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute-node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "configure pm2 to start as a service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu